### ISSUE TITLE
InsecurePlatformWarning: A true SSLContext object is not available.

### ISSUE THREAD

**Issue by niderhoff** [chrippa/livestreamer#819]
Hello, when trying to use livestreamer on OSX with the built-in python I get the following error:

livestreamer twitch.tv/sing_sing
[cli][info] Found matching plugin twitch for URL twitch.tv/sing_sing
/Library/Python/2.7/site-packages/requests-2.6.0-py2.7.egg/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

and then the program aborts. what is the issue here?

**Comment by chrippa** [comment]
As the link in the error sugests, your Python version can't reliably be used for SSL connections. Either upgrade your Python or [install an alternative SSL implementation](https://urllib3.readthedocs.org/en/latest/security.html#pyopenssl).

**Comment by xenio** [comment]
I also have this problem on Mac OS, could you please give some direction how to fix it? I am not very skilled with python. Thanks

**Comment by chhe** [comment]
I had the same problem on Raspbian (Debian for Raspberry Pi). I was able to fix it by re-installing the `requests` package with this command:

```
pip install requests[security]
```

Assuming you have installed `livestreamer` through `pip` like me you can do the same. Although I have no idea how or even if these things work on Mac OS. Be warned: you need a working `gcc` and the Python header files installed.

**Comment by falkuh** [comment]
Same problem here (Yosemite 10.10.3, python 2.7.9 installed. python -V gives 2.7.9).  I did:

`sudo -H pip install --upgrade certifi pyopenssl requests[security] ndg-httpsclient pyasn1 pip
sudo easy_install -U livestreamer
livestreamer http://www.twitch.tv/day9tv best`

and get:

`[cli][info] Found matching plugin twitch for URL http://www.twitch.tv/day9tv
/Library/Python/2.7/site-packages/requests-2.6.2-py2.7.egg/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
error: No streams found on this URL: http://www.twitch.tv/day9tv`

Any clue somebody ?

**Comment by Caf** [comment]
After much tinkering (I'm not a coder, not a terminal god, etc. :x )  I found that for some reason it was working flawlessly on my MacBook Pro but I got this error on the Mac Mini. It was because at 1st, my installation of livestreamer got sent into my old Python folder (in /Library/Python/2.7/ etc.) and all the fix I did with [Brew](http://brew.sh) where in /usr/local/lib/python2.7 (upgrade of python, SSL & co). So I just deleted the old livestreamer install, launched the script again and FIXED. Hope this will help some people. Each case is VERY specific with so many possibilities.

**Comment by tp0** [comment]
*chhe's* solution worked for me (Ubuntu, installed via pip).

**Comment by saeeda** [comment]
Getting this error

/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning


Error was resolved by

``` 
sudo pip install urllib3[secure] --upgrade

**Comment by 97yogitha** [comment]
Install these packages if u get insecure platform warning or of you find somewhere ssl object not found Build essential,python dev,libffi-dev,libssl-dev
and then
run the command 
sudo pip install urllib3

This should work

**Comment by Marslo** [comment]
@97yogitha Thanks! urllib3 works for me!!

**Comment by LockGit** [comment]
sudo pip install urllib3
can solve this question.
thanks

**Comment by pranav93** [comment]
I have installed urllib3 and also upgraded but it is not resolved. It shows "This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning."

What should i do so it run?

**Comment by jadhavmanoj** [comment]
I have installed urllib3 and also upgraded but it is not resolved. It shows "This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning."

What should i do so it run?

**Comment by RyuuZaky** [comment]
Thank you @chhe that worked for we as well

**Comment by khanhney** [comment]
I have same problems, but i tried uninstall 2.7 and I installed 2.7.9. really fix this problem
