### ISSUE TITLE
error after install, traceback is difficult to understand 

### ISSUE THREAD

**Issue by cocodrino** [chrippa/livestreamer#940]
Hi, I downloaded the livestreamer package using pip, when I try use it I get this error (notice than also I get the same error when listing plugins)

$ livestreamer --plugins
Traceback (most recent call last):
  File "/usr/local/bin/livestreamer", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 2603, in <module>
    #       =><
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 666, in require
    
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 565, in resolve
    
pkg_resources.DistributionNotFound: singledispatch

**Comment by chrippa** [comment]
Not sure why it would not have been installed automatically, but installing `singledispatch` via pip should solve the issue.

**Comment by cocodrino** [comment]
hi, seems than that package is already installed

$ sudo pip install singledispatch --upgrade
Requirement already up-to-date: singledispatch in /usr/local/lib/python2.7/dist-packages
Cleaning up...
```shell
$ livestreamer --plugins
Traceback (most recent call last):
File "/usr/local/bin/livestreamer", line 5, in 
from pkg_resources import load_entry_point
File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 2603, in 
# =><
File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 666, in require

File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 565, in resolve

pkg_resources.DistributionNotFound: singledispatch
```

I tried reinstall livestreamer again but the error persist, I'm using linux elementary luna btw...
please let me know if I can do something or give you more details.....

**Comment by chrippa** [comment]
Hmm, perhaps you can try uninstalling both via `pip uninstall` and then install Livestreamer again. Also check if you have a distribution package for singledispatch installed which might interfere somehow.

**Comment by cocodrino** [comment]
hi..nope, it seems not works..this is all the logs (not sure but seems exist some problem with a package named requests, I've got the package 2.7 but the logs show me some incompatibilities, I don't know so much about python ecosystem)

```shell
Storing debug log for failure in /home/yo/.pip/pip.log

# yo at yo in ~/Downloads/proj/scalaPROJ/finatra2/finatra/examples/finatra-hello-world on git:master x [11:47:09]
$ sudo pip uninstall singledispatch
[sudo] password for yo: 
Uninstalling singledispatch:
  /usr/local/lib/python2.7/dist-packages/singledispatch-3.4.0.3.dist-info/DESCRIPTION.rst
  /usr/local/lib/python2.7/dist-packages/singledispatch-3.4.0.3.dist-info/METADATA
  /usr/local/lib/python2.7/dist-packages/singledispatch-3.4.0.3.dist-info/RECORD
  /usr/local/lib/python2.7/dist-packages/singledispatch-3.4.0.3.dist-info/WHEEL
  /usr/local/lib/python2.7/dist-packages/singledispatch-3.4.0.3.dist-info/metadata.json
  /usr/local/lib/python2.7/dist-packages/singledispatch-3.4.0.3.dist-info/top_level.txt
  /usr/local/lib/python2.7/dist-packages/singledispatch-3.4.0.3.dist-info/zip-safe
  /usr/local/lib/python2.7/dist-packages/singledispatch.py
  /usr/local/lib/python2.7/dist-packages/singledispatch.pyc
  /usr/local/lib/python2.7/dist-packages/singledispatch_helpers.py
  /usr/local/lib/python2.7/dist-packages/singledispatch_helpers.pyc
Proceed (y/n)? y
  Successfully uninstalled singledispatch

# yo at yo in ~/Downloads/proj/scalaPROJ/finatra2/finatra/examples/finatra-hello-world on git:master x [11:47:18]
$ sudo pip uninstall livestreamer  
Uninstalling livestreamer:
  /usr/local/bin/livestreamer
  /usr/local/lib/python2.7/dist-packages/livestreamer-1.12.2-py2.7.egg-info
  /usr/local/lib/python2.7/dist-packages/livestreamer/__init__.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/api.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/api.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/buffers.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/buffers.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/cache.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/cache.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/compat.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/compat.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/exceptions.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/exceptions.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/logger.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/logger.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/options.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/options.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/packages/__init__.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/packages/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/packages/flashmedia/__init__.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/packages/flashmedia/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/packages/flashmedia/amf.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/packages/flashmedia/amf.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/packages/flashmedia/box.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/packages/flashmedia/box.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/packages/flashmedia/compat.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/packages/flashmedia/compat.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/packages/flashmedia/error.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/packages/flashmedia/error.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/packages/flashmedia/f4v.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/packages/flashmedia/f4v.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/packages/flashmedia/flv.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/packages/flashmedia/flv.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/packages/flashmedia/ordereddict.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/packages/flashmedia/ordereddict.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/packages/flashmedia/packet.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/packages/flashmedia/packet.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/packages/flashmedia/tag.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/packages/flashmedia/tag.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/packages/flashmedia/types.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/packages/flashmedia/types.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/packages/flashmedia/util.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/packages/flashmedia/util.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/packages/pbs.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/packages/pbs.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugin/__init__.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugin/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugin/api/__init__.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugin/api/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugin/api/http_session.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugin/api/http_session.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugin/api/mapper.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugin/api/mapper.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugin/api/support_plugin.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugin/api/support_plugin.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugin/api/utils.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugin/api/utils.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugin/api/validate.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugin/api/validate.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugin/plugin.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugin/plugin.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/__init__.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/afreeca.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/afreeca.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/afreecatv.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/afreecatv.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/aftonbladet.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/aftonbladet.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/alieztv.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/alieztv.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/ard_live.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/ard_live.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/ard_mediathek.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/ard_mediathek.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/artetv.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/artetv.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/azubutv.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/azubutv.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/bambuser.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/bambuser.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/beattv.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/beattv.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/chaturbate.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/chaturbate.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/common_jwplayer.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/common_jwplayer.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/common_swf.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/common_swf.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/connectcast.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/connectcast.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/crunchyroll.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/crunchyroll.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/cybergame.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/cybergame.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/dailymotion.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/dailymotion.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/disney_de.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/disney_de.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/dmcloud.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/dmcloud.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/dmcloud_embed.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/dmcloud_embed.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/dommune.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/dommune.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/douyutv.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/douyutv.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/drdk.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/drdk.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/euronews.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/euronews.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/filmon.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/filmon.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/filmon_us.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/filmon_us.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/furstream.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/furstream.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/gaminglive.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/gaminglive.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/gomexp.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/gomexp.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/goodgame.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/goodgame.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/hitbox.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/hitbox.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/itvplayer.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/itvplayer.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/letontv.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/letontv.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/livestation.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/livestation.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/livestream.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/livestream.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/media_ccc_de.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/media_ccc_de.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/mips.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/mips.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/mlgtv.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/mlgtv.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/nhkworld.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/nhkworld.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/nos.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/nos.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/npo.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/npo.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/nrk.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/nrk.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/oldlivestream.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/oldlivestream.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/periscope.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/periscope.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/picarto.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/picarto.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/rtve.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/rtve.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/sbsdiscovery.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/sbsdiscovery.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/seemeplay.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/seemeplay.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/speedrunslive.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/speedrunslive.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/ssh101.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/ssh101.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/stream.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/stream.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/streamingvideoprovider.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/streamingvideoprovider.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/streamlive.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/streamlive.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/svtplay.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/svtplay.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/tga.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/tga.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/tv3cat.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/tv3cat.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/tv4play.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/tv4play.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/tvcatchup.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/tvcatchup.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/tvplayer.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/tvplayer.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/twitch.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/twitch.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/ustreamtv.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/ustreamtv.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/vaughnlive.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/vaughnlive.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/veetle.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/veetle.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/vgtv.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/vgtv.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/viagame.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/viagame.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/viasat.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/viasat.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/viasat_embed.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/viasat_embed.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/wattv.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/wattv.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/weeb.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/weeb.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/youtube.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/youtube.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/zdf_mediathek.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/plugins/zdf_mediathek.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/session.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/session.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/stream/__init__.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/stream/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/stream/akamaihd.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/stream/akamaihd.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/stream/flvconcat.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/stream/flvconcat.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/stream/hds.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/stream/hds.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/stream/hls.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/stream/hls.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/stream/hls_playlist.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/stream/hls_playlist.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/stream/http.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/stream/http.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/stream/playlist.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/stream/playlist.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/stream/rtmpdump.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/stream/rtmpdump.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/stream/segmented.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/stream/segmented.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/stream/stream.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/stream/stream.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/stream/streamprocess.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/stream/streamprocess.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/stream/wrappers.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/stream/wrappers.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer/utils.py
  /usr/local/lib/python2.7/dist-packages/livestreamer/utils.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer_cli/__init__.py
  /usr/local/lib/python2.7/dist-packages/livestreamer_cli/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer_cli/argparser.py
  /usr/local/lib/python2.7/dist-packages/livestreamer_cli/argparser.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer_cli/compat.py
  /usr/local/lib/python2.7/dist-packages/livestreamer_cli/compat.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer_cli/console.py
  /usr/local/lib/python2.7/dist-packages/livestreamer_cli/console.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer_cli/constants.py
  /usr/local/lib/python2.7/dist-packages/livestreamer_cli/constants.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer_cli/main.py
  /usr/local/lib/python2.7/dist-packages/livestreamer_cli/main.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer_cli/output.py
  /usr/local/lib/python2.7/dist-packages/livestreamer_cli/output.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer_cli/packages/__init__.py
  /usr/local/lib/python2.7/dist-packages/livestreamer_cli/packages/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer_cli/packages/shutil_backport.py
  /usr/local/lib/python2.7/dist-packages/livestreamer_cli/packages/shutil_backport.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer_cli/utils/__init__.py
  /usr/local/lib/python2.7/dist-packages/livestreamer_cli/utils/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer_cli/utils/http_server.py
  /usr/local/lib/python2.7/dist-packages/livestreamer_cli/utils/http_server.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer_cli/utils/named_pipe.py
  /usr/local/lib/python2.7/dist-packages/livestreamer_cli/utils/named_pipe.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer_cli/utils/player.py
  /usr/local/lib/python2.7/dist-packages/livestreamer_cli/utils/player.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer_cli/utils/progress.py
  /usr/local/lib/python2.7/dist-packages/livestreamer_cli/utils/progress.pyc
  /usr/local/lib/python2.7/dist-packages/livestreamer_cli/utils/stream.py
  /usr/local/lib/python2.7/dist-packages/livestreamer_cli/utils/stream.pyc
Proceed (y/n)? y
  Successfully uninstalled livestreamer

# yo at yo in ~/Downloads/proj/scalaPROJ/finatra2/finatra/examples/finatra-hello-world on git:master x [11:47:48]
$ sudo pip install singledispatch 
Downloading/unpacking singledispatch
  Downloading singledispatch-3.4.0.3-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python2.7/dist-packages (from singledispatch)
Installing collected packages: singledispatch
Successfully installed singledispatch
Cleaning up...

# yo at yo in ~/Downloads/proj/scalaPROJ/finatra2/finatra/examples/finatra-hello-world on git:master x [11:48:27]
$ sudo pip install livestreamer 
Downloading/unpacking livestreamer
  Downloading livestreamer-1.12.2.tar.gz (430kB): 430kB downloaded
  Running setup.py (path:/tmp/pip_build_root/livestreamer/setup.py) egg_info for package livestreamer
    
    warning: no files found matching 'AUTHORS'
Requirement already satisfied (use --upgrade to upgrade): futures in /usr/local/lib/python2.7/dist-packages (from livestreamer)
Requirement already satisfied (use --upgrade to upgrade): singledispatch in /usr/local/lib/python2.7/dist-packages (from livestreamer)
Requirement already satisfied (use --upgrade to upgrade): requests>=1.0,<3.0 in /usr/local/lib/python2.7/dist-packages (from livestreamer)
Installing collected packages: livestreamer
  Running setup.py install for livestreamer
    
    warning: no files found matching 'AUTHORS'
    Installing livestreamer script to /usr/local/bin
Successfully installed livestreamer
Cleaning up...

# yo at yo in ~/Downloads/proj/scalaPROJ/finatra2/finatra/examples/finatra-hello-world on git:master x [11:49:39]
$ livestreamer --plugins
Traceback (most recent call last):
  File "/usr/local/bin/livestreamer", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 2603, in <module>
    #       =><
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 666, in require
    
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 565, in resolve
    
pkg_resources.DistributionNotFound: requests>=1.0,<3.0

# yo at yo in ~/Downloads/proj/scalaPROJ/finatra2/finatra/examples/finatra-hello-world on git:master x [11:49:57]
$ sudo pip install requests              
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/local/lib/python2.7/dist-packages
Cleaning up...

# yo at yo in ~/Downloads/proj/scalaPROJ/finatra2/finatra/examples/finatra-hello-world on git:master x [11:50:58]
$ sudo pip uninnstall requests
ERROR: unknown command "uninnstall" - maybe you meant "uninstall"

# yo at yo in ~/Downloads/proj/scalaPROJ/finatra2/finatra/examples/finatra-hello-world on git:master x [11:51:08]
$ sudo pip uninstall requests 
Uninstalling requests:
  /usr/local/lib/python2.7/dist-packages/requests-2.4.3.dist-info/DESCRIPTION.rst
  /usr/local/lib/python2.7/dist-packages/requests-2.4.3.dist-info/METADATA
  /usr/local/lib/python2.7/dist-packages/requests-2.4.3.dist-info/RECORD
  /usr/local/lib/python2.7/dist-packages/requests-2.4.3.dist-info/WHEEL
  /usr/local/lib/python2.7/dist-packages/requests-2.4.3.dist-info/pydist.json
  /usr/local/lib/python2.7/dist-packages/requests-2.4.3.dist-info/top_level.txt
  /usr/local/lib/python2.7/dist-packages/requests/__init__.py
  /usr/local/lib/python2.7/dist-packages/requests/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/requests/adapters.py
  /usr/local/lib/python2.7/dist-packages/requests/adapters.pyc
  /usr/local/lib/python2.7/dist-packages/requests/api.py
  /usr/local/lib/python2.7/dist-packages/requests/api.pyc
  /usr/local/lib/python2.7/dist-packages/requests/auth.py
  /usr/local/lib/python2.7/dist-packages/requests/auth.pyc
  /usr/local/lib/python2.7/dist-packages/requests/cacert.pem
  /usr/local/lib/python2.7/dist-packages/requests/certs.py
  /usr/local/lib/python2.7/dist-packages/requests/certs.pyc
  /usr/local/lib/python2.7/dist-packages/requests/compat.py
  /usr/local/lib/python2.7/dist-packages/requests/compat.pyc
  /usr/local/lib/python2.7/dist-packages/requests/cookies.py
  /usr/local/lib/python2.7/dist-packages/requests/cookies.pyc
  /usr/local/lib/python2.7/dist-packages/requests/exceptions.py
  /usr/local/lib/python2.7/dist-packages/requests/exceptions.pyc
  /usr/local/lib/python2.7/dist-packages/requests/hooks.py
  /usr/local/lib/python2.7/dist-packages/requests/hooks.pyc
  /usr/local/lib/python2.7/dist-packages/requests/models.py
  /usr/local/lib/python2.7/dist-packages/requests/models.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/__init__.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/__init__.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/big5freq.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/big5freq.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/big5prober.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/big5prober.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/chardetect.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/chardetect.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/chardistribution.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/chardistribution.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/charsetgroupprober.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/charsetgroupprober.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/charsetprober.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/charsetprober.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/codingstatemachine.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/codingstatemachine.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/compat.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/compat.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/constants.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/constants.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/cp949prober.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/cp949prober.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/escprober.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/escprober.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/escsm.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/escsm.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/eucjpprober.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/eucjpprober.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/euckrfreq.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/euckrfreq.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/euckrprober.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/euckrprober.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/euctwfreq.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/euctwfreq.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/euctwprober.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/euctwprober.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/gb2312freq.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/gb2312freq.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/gb2312prober.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/gb2312prober.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/hebrewprober.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/hebrewprober.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/jisfreq.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/jisfreq.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/jpcntx.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/jpcntx.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/langbulgarianmodel.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/langbulgarianmodel.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/langcyrillicmodel.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/langcyrillicmodel.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/langgreekmodel.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/langgreekmodel.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/langhebrewmodel.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/langhebrewmodel.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/langhungarianmodel.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/langhungarianmodel.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/langthaimodel.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/langthaimodel.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/latin1prober.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/latin1prober.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/mbcharsetprober.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/mbcharsetprober.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/mbcsgroupprober.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/mbcsgroupprober.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/mbcssm.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/mbcssm.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/sbcharsetprober.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/sbcharsetprober.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/sbcsgroupprober.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/sbcsgroupprober.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/sjisprober.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/sjisprober.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/universaldetector.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/universaldetector.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/utf8prober.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/chardet/utf8prober.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/__init__.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/_collections.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/_collections.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connection.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connection.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/__init__.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/ntlmpool.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/ntlmpool.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/exceptions.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/exceptions.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/fields.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/fields.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/filepost.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/filepost.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/packages/__init__.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/packages/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/packages/ordered_dict.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/packages/ordered_dict.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/packages/six.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/packages/six.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/packages/ssl_match_hostname/__init__.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/packages/ssl_match_hostname/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/packages/ssl_match_hostname/_implementation.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/packages/ssl_match_hostname/_implementation.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/poolmanager.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/poolmanager.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/request.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/request.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/response.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/response.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/__init__.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/connection.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/connection.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/request.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/request.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/response.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/response.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/retry.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/retry.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/timeout.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/timeout.pyc
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/url.py
  /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/url.pyc
  /usr/local/lib/python2.7/dist-packages/requests/sessions.py
  /usr/local/lib/python2.7/dist-packages/requests/sessions.pyc
  /usr/local/lib/python2.7/dist-packages/requests/status_codes.py
  /usr/local/lib/python2.7/dist-packages/requests/status_codes.pyc
  /usr/local/lib/python2.7/dist-packages/requests/structures.py
  /usr/local/lib/python2.7/dist-packages/requests/structures.pyc
  /usr/local/lib/python2.7/dist-packages/requests/utils.py
  /usr/local/lib/python2.7/dist-packages/requests/utils.pyc
Proceed (y/n)? y
  Successfully uninstalled requests

 
# yo at yo in ~/Downloads/proj/scalaPROJ/finatra2/finatra/examples/finatra-hello-world on git:master x [11:51:16]
$ sudo pip install requests   
Downloading/unpacking requests
  Downloading requests-2.7.0-py2.py3-none-any.whl (470kB): 470kB downloaded
Installing collected packages: requests
Successfully installed requests
Cleaning up...

# yo at yo in ~/Downloads/proj/scalaPROJ/finatra2/finatra/examples/finatra-hello-world on git:master x [11:51:44]
$ livestreamer --plugins       
Traceback (most recent call last):
  File "/usr/local/bin/livestreamer", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 2603, in <module>
    #       =><
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 666, in require
    
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 565, in resolve
    
pkg_resources.DistributionNotFound: requests>=1.0,<3.0


```

**Comment by chrippa** [comment]
Hmm, one more thing you can try is `easy_install -U requests singledispatch livestreamer`.

**Comment by cocodrino** [comment]
finally it works!! easy_install do the job, maybe would be nice add this option in the doc as alternative to pip for people than doesnt known so much about the python environment...thanks!!!...

**Comment by tolsadus** [comment]
damn thanks @chrippa
